# Generated by Django 4.2.16 on 2024-11-28 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=200, unique=True)),
                ('appt_date', models.DateField(default=datetime.date(2024, 11, 28))),
                ('appt_time', models.TimeField()),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Attended'), (2, 'Cancelled'), (3, 'Rescheduled')], default=0, max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('followup_details', models.TextField(blank=True, null=True)),
                ('travel_details', models.TextField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_appt.consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
