# Generated by Django 4.2.16 on 2024-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_appt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='specialty',
            field=models.CharField(default='General Practitioner', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Attended'), (2, 'Cancelled'), (3, 'Rescheduled')], default=0),
        ),
    ]
