# Generated by Django 4.2.16 on 2024-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_appt', '0002_consultant_specialty_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='institution',
            field=models.CharField(default='No Institution/Hospital set', max_length=100),
        ),
    ]
