# Generated by Django 4.2.16 on 2024-11-29 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_appt', '0003_consultant_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(default=datetime.date(2024, 11, 29)),
        ),
    ]
