# Generated by Django 4.2.16 on 2024-11-29 14:55

from django.db import migrations, models

def convert_status_to_charfield(apps, schema_editor):
    Appointment = apps.get_model('med_appt', 'Appointment')
    for obj in Appointment.objects.all():
        if obj.status == 0:
            obj.status = 'Pending'
        elif obj.status == 1:
            obj.status = 'Attended'
        elif obj.status == 2:
            obj.status = 'Cancelled'
        elif obj.status == 3:
            obj.status = 'Rescheduled'
    obj.save()

STATUS = (
    ('Pending', 'Pending'),
    ('Attended', 'Attended'), 
    ('Cancelled', 'Cancelled'),
    ('Rescheduled', 'Rescheduled'),
)

class Migration(migrations.Migration):

    dependencies = [
        ('med_appt', '0004_alter_appointment_appt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Appointment',
            name='status',
            field=models.CharField(choices=STATUS, default='Pending', max_length=20),
        ),
        migrations.RunPython(convert_status_to_charfield),
    ]
