# Generated by Django 4.2.16 on 2024-11-30 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med_appt', '0007_alter_appointment_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
