# Generated by Django 4.2.16 on 2024-12-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_populate_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med_appt', '0008_alter_appointment_appt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultant_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='consultant',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='consultants', to='user_profile.profile'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='consultant',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='med_appt.consultant'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
